# Generated by Django 4.2.3 on 2024-02-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_pricelist_pricelistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='opening_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
